name: Deno Windows Build

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: 'latest'

    - name: Build for Windows (x86_64)
      run: |
        deno compile --unstable-raw-imports --unstable-kv --allow-all --include=data.d.ts --include templates --include static  --output=app.exe exe.ts
        # 如果你的入口文件不是main.ts，请替换为你的实际入口文件
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: app.exe