name: Denovel Cross-Platform Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0
    

jobs:
  build:
    name: Build Denovel
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, ubuntu-latest]
        arch: [x64, x64, x64, arm64]
        include:
          - os: ubuntu-latest
            arch: x64
            artifact_name: denovel-linux-x64
            bin_ext: ''
          - os: macos-latest
            arch: x64
            artifact_name: denovel-macos-x64
            bin_ext: ''
          - os: windows-latest
            arch: x64
            artifact_name: denovel-windows-x64
            bin_ext: '.exe'
          - os: ubuntu-latest
            arch: arm64
            artifact_name: denovel-linux-arm64
            bin_ext: ''
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: latest

    - name: Install Denovel dependencies
      run: deno install
        
    - name: Install dependencies
      run: deno cache --unstable-raw-imports --unstable-kv exe.ts
      
    - name: Setup QEMU (for ARM64 cross-compilation)
      if: matrix.arch == 'arm64'
      uses: docker/setup-qemu-action@v3
      
    - name: Compile to binary
      run: |
        if [ "${{ matrix.arch }}" = "arm64" ]; then
          deno compile --target aarch64-unknown-linux-gnu --unstable-raw-imports --unstable-kv --allow-all --include=data.d.ts --no-check --include templates --include static --output=${{ matrix.artifact_name }}${{ matrix.bin_ext }} exe.ts
        else
          deno compile --unstable-raw-imports --unstable-kv --allow-all --include=data.d.ts --no-check --include templates --include static --output=${{ matrix.artifact_name }}${{ matrix.bin_ext }} exe.ts
        fi
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ matrix.artifact_name }}${{ matrix.bin_ext }}
        if-no-files-found: error
        
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        
    - name: List downloaded artifacts
      run: ls -la artifacts/
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/**/*
        generate_release_notes: true
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
