name: Build and Release Deno Binary

on:
  push:
    tags: ["v*"]  # 仅当打tag时触发 (例如 v1.0.0)
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: myapp-linux
            ext: ""
          - os: macos-latest
            artifact_name: myapp-macos
            ext: ""
          - os: windows-latest
            artifact_name: myapp-windows
            ext: ".exe"
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: "1.40"

    - name: Build executable
      run: |
        deno compile \
          --allow-read --allow-write --allow-net \
          --allow-run --allow-env \
          --output=./dist/${{ matrix.artifact_name }} \
          exe.ts

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact_name }}
        path: ./dist/${{ matrix.artifact_name }}${{ matrix.ext }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')  # 仅tag触发

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: "Pre-built binaries for Linux, macOS and Windows"
        files: |
          artifacts/myapp-linux
          artifacts/myapp-macos
          artifacts/myapp-windows.exe
